### ISSUE TITLE
Compiling with mingw fails on ubuntu 20.04

### ISSUE THREAD

**Issue by mihaly-sisak** [nih-at/libzip#461]
**Compiler Error**
```
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0xf0): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x110): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x130): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x360): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x40d): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x8cc): more undefined references to `__imp_zip_error_set' follow
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x118b): undefined reference to `__imp_zip_source_seek'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x12ca): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1322): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1340): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1362): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1389): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x13ab): more undefined references to `__imp_zip_error_set' follow
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x140d): undefined reference to `__imp_zip_error_code_zip'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1458): undefined reference to `__imp_zip_source_seek'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1485): undefined reference to `__imp_zip_source_seek'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1505): undefined reference to `__imp_zip_error_set_from_source'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x151e): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1a8e): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1b46): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1b73): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1c0b): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x1d14): undefined reference to `__imp_zip_source_tell_write'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x2082): undefined reference to `__imp_zip_error_set_from_source'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x20a0): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x20d7): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x21cd): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x21f2): undefined reference to `__imp_zip_error_set'
/usr/bin/x86_64-w64-mingw32-ld: lib/CMakeFiles/zip.dir/zip_dirent.c.obj:zip_dirent.c:(.text+0x22a4): undefined reference to `__imp_zip_error_set'
```

**libzip Version**
zlib-1.3.1 + libzip-1.11.1

**Operating System and Compiler**
Ubuntu 20.04 + mingw (x86_64-w64-mingw32-gcc (GCC) 10-posix 20220113, from the official ubuntu repo)
Also, any flags passed to `cmake`.
Documented below in script.

**Autodetected Configuration**
Attach `CmakeCache.txt` from your build directory. This list everything `cmake` detected on your system.
[CMakeCache.txt](https://github.com/user-attachments/files/17257056/CMakeCache.txt)

**Additional context**
Added script to reproduce the problem. I am using mingw-w64 with posix implementation, trying to build zlib-1.3.1 + libzip-1.11.1. Commented out the mingw-w64 installation command and the posix implementations set command.
Worked on libzip-1.10.1 + zlib-1.3.1.
[libzip_bugreport.sh.txt](https://github.com/user-attachments/files/17257067/libzip_bugreport.sh.txt)

**Comment by 0-wiz-0** [comment]
I'm pretty sure this is the same as https://github.com/nih-at/libzip/issues/457 and there's a fix in the repository - can you please check?

**Comment by mihaly-sisak** [comment]
Thank you very much, it worked!
