### ISSUE TITLE
erors building on OSX v 1.5.0

### ISSUE THREAD

**Issue by gaming-hacker** [nih-at/libzip#36]
hello,
trying to build on OSX 10.12.6, errors out with the following.

can someone confirm this is a simple typo? that fragments s.b. nfragments?

```
ziptool_regress.c:162:6: error: use of undeclared identifier 'zip_buffer_fragment_t'
:info:build             zip_buffer_fragment_t *fragments;

ptool_regress.c:161:19: note: 'nfragments' declared here
:info:build             zip_uint64_t nfragments, i, left;
:info:build                          ^

ziptool_regress.c:165:37: error: use of undeclared identifier 'fragments'
:info:build             if ((fragments = malloc(sizeof(fragments[0]) * nfragments)) == NULL) {

ziptool_regress.c:172:8: error: use of undeclared identifier 'fragments'
:info:build                 if ((fragments[i].data = malloc(left)) == NULL) {

ziptool_regress.c:176:9: error: use of undeclared identifier 'fragments'
:info:build                         free(fragments[i].data);
```

**Comment by 0-wiz-0** [comment]
I'm guessing you have an older version of libzip installed, and its `zip.h` header is found first.
Travis tells us that it's generally building on macOS.

**Comment by gaming-hacker** [comment]
yes currently 1.3.2 and upgrading to 1.5.0.  ok, let me dig a little deeper but i installed this via macports and see what pkconfig is looking at.

**Comment by gaming-hacker** [comment]
yes currently 1.3.2 and upgrading to 1.5.0.  ok, let me dig a little deeper but i installed this via macports and see what pkconfig is looking at.

**Comment by 0-wiz-0** [comment]
We've tried fixing this with https://github.com/nih-at/libzip/commit/4cd3c601cb48be89cd9e6e5082cc7bbe47e8a003
Can you please try the latest git version and check if it fixes your problem?

**Comment by gaming-hacker** [comment]
Yes, it's fixed, thanks!
